# Generated by Django 3.0.6 on 2020-06-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_name', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
