# Generated by Django 3.0.6 on 2020-07-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(height_field='height', upload_to='images/photos', width_field='width'),
        ),
    ]
